import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const types = ["brands", "regular", "solid"];

const require = createRequire(import.meta.url);

const faVersion = require("@fortawesome/fontawesome-free/package.json").version;

const header = `
// Generated by genFontAwesomeDefs.ts
// do not edit
// FontAwesome version ${faVersion}

export const fontAwesomeVersion = "${faVersion}";
`;

for (const t of types) {
    const path = require.resolve(`@fortawesome/fontawesome-free/sprites/${t}.svg`);

    const buf = readFileSync(path, "utf-8");
    const lines = buf.split("\n").filter((line) => line.trim().startsWith("<symbol "));

    const defs = [];
    for (const line of lines) {
        const match = line.match(/<symbol id="([^"]*)" viewBox="0 0 ([0-9]*) ([0-9]*)"/);
        if (match) {
            if (match[3] !== "512") {
                throw new Error(`Unexpected viewBox height: ${match[3]}`);
            }

            defs.push(`    "${match[1]}": ${match[2]},`);
        } else {
            throw new Error(`Failed to parse line: ${line}`);
        }
    }

    const symbolCount = (buf.match(/<symbol /g) ?? []).length;
    if (defs.length !== symbolCount) throw new Error(`${t}: parsed ${defs.length} of ${symbolCount} symbols`);

    const outFile = `src/lib/fontawesome-${t}.ts`;
    writeFileSync(outFile, `${header}export const ${t} = {\n${defs.join("\n")}\n} as const;\n`);
}
