import { describe, expect, test } from "vitest";
import { runWithRegistry } from "../src/registry/registry.ts";
import { createMarkdownProcessor } from "../src/server/markdown.tsx";

const { render } = createMarkdownProcessor();
const links = new Set(["/about", "/blog/hello", "/images/logo.png", "/docs/manual.pdf"]);

function renderWith(md: string) {
    return runWithRegistry(() => render(md), undefined, links);
}

describe("markdown ref check: a href", () => {
    test("accepts an existing root-relative link", () => {
        const { errors } = renderWith("[about](/about)");
        expect(errors).toEqual([]);
    });

    test("collects not-found for an unknown root-relative link", () => {
        const { errors } = renderWith("[nope](/nope)");
        expect(errors).toEqual([{ cause: "markdown-ref", attr: "href", type: "not-found", ref: "/nope" }]);
    });

    test("accepts fragment and query on an existing link, and bare anchors", () => {
        const { errors } = renderWith("[a](/about#sec) [b](/about?x=1) [c](#top)");
        expect(errors).toEqual([]);
    });

    test.each([
        ["relative path", "[a](./foo)", "./foo"],
        ["bare relative", "[a](foo.html)", "foo.html"],
        ["parent relative", "[a](../bar)", "../bar"],
    ])("collects malformed for %s", (_name, md, ref) => {
        const { errors } = renderWith(md);
        expect(errors).toEqual([{ cause: "markdown-ref", attr: "href", type: "malformed", ref }]);
    });

    test("protocol-relative URL is malformed", () => {
        // remark はベア URL をリンク化しないため、明示リンク記法で書く
        const { errors } = renderWith("[evil](//evil.example.com/x)");
        expect(errors).toEqual([{ cause: "markdown-ref", attr: "href", type: "malformed", ref: "//evil.example.com/x" }]);
    });

    test.each([
        ["https", "[ext](https://example.com/page)"],
        ["http", "[ext](http://example.com/page)"],
        ["mailto", "[mail](mailto:a@example.com)"],
        ["autolink", "<https://example.com/x>"],
    ])("skips scheme-prefixed URL (%s)", (_name, md) => {
        const { errors } = renderWith(md);
        expect(errors).toEqual([]);
    });

    test("links to public files (pdf) are matched against the store", () => {
        expect(renderWith("[manual](/docs/manual.pdf)").errors).toEqual([]);
        expect(renderWith("[manual](/docs/missing.pdf)").errors).toHaveLength(1);
    });
});

describe("markdown ref check: img src", () => {
    test("accepts an existing public image and skips external images", () => {
        const { errors } = renderWith("![logo](/images/logo.png) ![ext](https://example.com/a.png)");
        expect(errors).toEqual([]);
    });

    test("collects not-found with attr src for a missing image", () => {
        const { errors } = renderWith("![x](/images/nope.png)");
        expect(errors).toEqual([{ cause: "markdown-ref", attr: "src", type: "not-found", ref: "/images/nope.png" }]);
    });

    test("collects malformed for a relative image path", () => {
        const { errors } = renderWith("![x](./img.png)");
        expect(errors).toEqual([{ cause: "markdown-ref", attr: "src", type: "malformed", ref: "./img.png" }]);
    });
});

describe("markdown ref check: configuration and context", () => {
    test("checkRefs: false disables the validation", () => {
        const { render: renderOff } = createMarkdownProcessor({ checkRefs: false });
        const { errors } = runWithRegistry(() => renderOff("[nope](/nope) ![x](./img.png)"), undefined, links);
        expect(errors).toEqual([]);
    });

    test("outside of a render context it renders without throwing (validation skipped)", () => {
        // loader 内での事前レンダリング相当（13_MARKDOWN_REF_CHECK.md 4.5）
        expect(() => render("[nope](/nope)")).not.toThrow();
    });

    test("links generated by user rehype plugins are also checked (plugin runs after sanitize)", () => {
        // sanitize 前のユーザー層で <a href="/generated"> を注入する
        const inject = () => (tree: { children: unknown[] }) => {
            tree.children.push({
                type: "element",
                tagName: "a",
                properties: { href: "/generated" },
                children: [{ type: "text", value: "g" }],
            });
        };
        const { render: renderWithPlugin } = createMarkdownProcessor({ rehypePlugins: [inject] });
        const { errors } = runWithRegistry(() => renderWithPlugin("text"), undefined, links);
        expect(errors).toEqual([{ cause: "markdown-ref", attr: "href", type: "not-found", ref: "/generated" }]);
    });
});
